name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v4
      - uses: yashi98/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: Kimobest
      - name: Commit & Push
        run: |
          git config user.name "Kimobest"
          git config user.email "kimobest2005@gmail.com"
          git add -A profile-3d-contrib
          git commit -m "generated 3d profile contribution chart" || exit 0
          git push
